<?php

if (!defined('ABSPATH')) exit;

$keywords = array(
    /**
     * Apps names
     */
    __('Instagram Feed', 'elfsight-elementor-extension'),
    __('YouTube Gallery', 'elfsight-elementor-extension'),
    __('Instagram Widget', 'elfsight-elementor-extension'),
    __('Social Media Icons', 'elfsight-elementor-extension'),
    __('Social Share Buttons', 'elfsight-elementor-extension'),
    __('Google Maps', 'elfsight-elementor-extension'),
    __('Facebook Feed', 'elfsight-elementor-extension'),
    __('Facebook Comments', 'elfsight-elementor-extension'),
    __('Facebook Like Button', 'elfsight-elementor-extension'),
    __('Facebook Share Button', 'elfsight-elementor-extension'),
    __('Pricing Table', 'elfsight-elementor-extension'),
    __('Instagram Testimonials', 'elfsight-elementor-extension'),
    __('Contact Form', 'elfsight-elementor-extension'),
    __('Testimonials Slider', 'elfsight-elementor-extension'),
    __('FAQ', 'elfsight-elementor-extension'),
    __('Form Builder', 'elfsight-elementor-extension'),
    __('Twitter Feed', 'elfsight-elementor-extension'),
    __('Paypal Button', 'elfsight-elementor-extension'),
    __('Countdown Timer', 'elfsight-elementor-extension'),
    __('Pinterest Feed', 'elfsight-elementor-extension'),
    __('Facebook Reviews', 'elfsight-elementor-extension'),
    __('Facebook Chat', 'elfsight-elementor-extension'),
    __('WhatsApp Chat', 'elfsight-elementor-extension'),
    __('Reviews from TripAdvisor', 'elfsight-elementor-extension'),
    __('Team Showcase', 'elfsight-elementor-extension'),
    __('Yelp Reviews', 'elfsight-elementor-extension'),
    __('PDF Embed', 'elfsight-elementor-extension'),
    __('File Embed', 'elfsight-elementor-extension'),
    __('Cookie Consent', 'elfsight-elementor-extension'),
    __('Google Reviews', 'elfsight-elementor-extension'),
    __('Age Verification', 'elfsight-elementor-extension'),
    __('Portfolio', 'elfsight-elementor-extension'),
    __('Booking Reviews', 'elfsight-elementor-extension'),
    __('Airbnb Reviews', 'elfsight-elementor-extension'),
    __('Vimeo Gallery', 'elfsight-elementor-extension'),
    __('Click To Call', 'elfsight-elementor-extension'),
    __('Popup', 'elfsight-elementor-extension'),
    __('Slider', 'elfsight-elementor-extension'),
    __('Telegram Chat', 'elfsight-elementor-extension'),
    __('Amazon Reviews', 'elfsight-elementor-extension'),
    __('G2 Crowd Reviews', 'elfsight-elementor-extension'),
    __('Weather', 'elfsight-elementor-extension'),
    __('Logo Showcase', 'elfsight-elementor-extension'),
    __('Event Calendar', 'elfsight-elementor-extension'),
    __('Trustpilot Reviews', 'elfsight-elementor-extension'),
    __('Apple App Store Reviews', 'elfsight-elementor-extension'),
    __('Photo Gallery', 'elfsight-elementor-extension'),
    __('Audio Player', 'elfsight-elementor-extension'),
    __('Podcast Player', 'elfsight-elementor-extension'),
    __('Background Music', 'elfsight-elementor-extension'),
    __('Viber Chat', 'elfsight-elementor-extension'),
    __('Before and After Slider', 'elfsight-elementor-extension'),
    __('Radio Player', 'elfsight-elementor-extension'),
    __('All-in-One Chat', 'elfsight-elementor-extension'),
    __('Back to Top', 'elfsight-elementor-extension'),
    __('QR Code', 'elfsight-elementor-extension'),
    __('Number Counter', 'elfsight-elementor-extension'),
    __('Restaurant Menu', 'elfsight-elementor-extension'),
    __('Visitor Counter', 'elfsight-elementor-extension'),
    __('Search', 'elfsight-elementor-extension'),
    __('All-in-One Reviews', 'elfsight-elementor-extension'),

    /**
     * Apps tags
     */
    __('profile', 'elfsight-elementor-extension'),
    __('username', 'elfsight-elementor-extension'),
    __('account', 'elfsight-elementor-extension'),
    __('hashtag', 'elfsight-elementor-extension'),
    __('location', 'elfsight-elementor-extension'),
    __('post', 'elfsight-elementor-extension'),
    __('posts', 'elfsight-elementor-extension'),
    __('video', 'elfsight-elementor-extension'),
    __('photo', 'elfsight-elementor-extension'),
    __('image', 'elfsight-elementor-extension'),
    __('slider', 'elfsight-elementor-extension'),
    __('carousel', 'elfsight-elementor-extension'),
    __('grid', 'elfsight-elementor-extension'),
    __('gallery', 'elfsight-elementor-extension'),
    __('portfolio', 'elfsight-elementor-extension'),
    __('timeline', 'elfsight-elementor-extension'),
    __('business', 'elfsight-elementor-extension'),
    __('tag', 'elfsight-elementor-extension'),
    __('follower', 'elfsight-elementor-extension'),
    __('shoppable', 'elfsight-elementor-extension'),
    __('social', 'elfsight-elementor-extension'),
    __('ig', 'elfsight-elementor-extension'),
    __('slideshow', 'elfsight-elementor-extension'),
    __('instashow', 'elfsight-elementor-extension'),
    __('playlist', 'elfsight-elementor-extension'),
    __('player', 'elfsight-elementor-extension'),
    __('channel', 'elfsight-elementor-extension'),
    __('user', 'elfsight-elementor-extension'),
    __('adsense', 'elfsight-elementor-extension'),
    __('vimeo', 'elfsight-elementor-extension'),
    __('popup', 'elfsight-elementor-extension'),
    __('content', 'elfsight-elementor-extension'),
    __('embed', 'elfsight-elementor-extension'),
    __('album', 'elfsight-elementor-extension'),
    __('follow', 'elfsight-elementor-extension'),
    __('list', 'elfsight-elementor-extension'),
    __('yottie', 'elfsight-elementor-extension'),
    __('instalink', 'elfsight-elementor-extension'),
    __('network', 'elfsight-elementor-extension'),
    __('link', 'elfsight-elementor-extension'),
    __('like', 'elfsight-elementor-extension'),
    __('logo', 'elfsight-elementor-extension'),
    __('png', 'elfsight-elementor-extension'),
    __('svg', 'elfsight-elementor-extension'),
    __('vector', 'elfsight-elementor-extension'),
    __('facebook', 'elfsight-elementor-extension'),
    __('twitter', 'elfsight-elementor-extension'),
    __('pinterest', 'elfsight-elementor-extension'),
    __('instagram', 'elfsight-elementor-extension'),
    __('youtube', 'elfsight-elementor-extension'),
    __('linkedin', 'elfsight-elementor-extension'),
    __('print', 'elfsight-elementor-extension'),
    __('media', 'elfsight-elementor-extension'),
    __('share', 'elfsight-elementor-extension'),
    __('sharing', 'elfsight-elementor-extension'),
    __('store', 'elfsight-elementor-extension'),
    __('place', 'elfsight-elementor-extension'),
    __('locator', 'elfsight-elementor-extension'),
    __('find', 'elfsight-elementor-extension'),
    __('marker', 'elfsight-elementor-extension'),
    __('address', 'elfsight-elementor-extension'),
    __('geolocation', 'elfsight-elementor-extension'),
    __('route', 'elfsight-elementor-extension'),
    __('fb', 'elfsight-elementor-extension'),
    __('albums', 'elfsight-elementor-extension'),
    __('videos', 'elfsight-elementor-extension'),
    __('news', 'elfsight-elementor-extension'),
    __('live', 'elfsight-elementor-extension'),
    __('photos', 'elfsight-elementor-extension'),
    __('events', 'elfsight-elementor-extension'),
    __('wall', 'elfsight-elementor-extension'),
    __('page', 'elfsight-elementor-extension'),
    __('activity', 'elfsight-elementor-extension'),
    __('group', 'elfsight-elementor-extension'),
    __('ecommerce', 'elfsight-elementor-extension'),
    __('e-commerce', 'elfsight-elementor-extension'),
    __('payment', 'elfsight-elementor-extension'),
    __('money', 'elfsight-elementor-extension'),
    __('paying', 'elfsight-elementor-extension'),
    __('currency', 'elfsight-elementor-extension'),
    __('checkout', 'elfsight-elementor-extension'),
    __('sale', 'elfsight-elementor-extension'),
    __('purchase', 'elfsight-elementor-extension'),
    __('buy', 'elfsight-elementor-extension'),
    __('price', 'elfsight-elementor-extension'),
    __('feature', 'elfsight-elementor-extension'),
    __('plan', 'elfsight-elementor-extension'),
    __('monthly', 'elfsight-elementor-extension'),
    __('yearly', 'elfsight-elementor-extension'),
    __('subscription', 'elfsight-elementor-extension'),
    __('review', 'elfsight-elementor-extension'),
    __('rating', 'elfsight-elementor-extension'),
    __('star', 'elfsight-elementor-extension'),
    __('feedback', 'elfsight-elementor-extension'),
    __('recommendation', 'elfsight-elementor-extension'),
    __('opinion', 'elfsight-elementor-extension'),
    __('experience', 'elfsight-elementor-extension'),
    __('customer', 'elfsight-elementor-extension'),
    __('client', 'elfsight-elementor-extension'),
    __('rotator', 'elfsight-elementor-extension'),
    __('booking', 'elfsight-elementor-extension'),
    __('survey', 'elfsight-elementor-extension'),
    __('request', 'elfsight-elementor-extension'),
    __('registration', 'elfsight-elementor-extension'),
    __('enquiry', 'elfsight-elementor-extension'),
    __('email', 'elfsight-elementor-extension'),
    __('message', 'elfsight-elementor-extension'),
    __('builder', 'elfsight-elementor-extension'),
    __('webform', 'elfsight-elementor-extension'),
    __('frequentlyaskedquestions', 'elfsight-elementor-extension'),
    __('accordion', 'elfsight-elementor-extension'),
    __('dropdown', 'elfsight-elementor-extension'),
    __('answer', 'elfsight-elementor-extension'),
    __('question', 'elfsight-elementor-extension'),
    __('tutorial', 'elfsight-elementor-extension'),
    __('step', 'elfsight-elementor-extension'),
    __('help', 'elfsight-elementor-extension'),
    __('support', 'elfsight-elementor-extension'),
    __('center', 'elfsight-elementor-extension'),
    __('typeform', 'elfsight-elementor-extension'),
    __('quiz', 'elfsight-elementor-extension'),
    __('poll', 'elfsight-elementor-extension'),
    __('order', 'elfsight-elementor-extension'),
    __('sign', 'elfsight-elementor-extension'),
    __('login', 'elfsight-elementor-extension'),
    __('mailchimp', 'elfsight-elementor-extension'),
    __('questionnaire', 'elfsight-elementor-extension'),
    __('creator', 'elfsight-elementor-extension'),
    __('generator', 'elfsight-elementor-extension'),
    __('tweet', 'elfsight-elementor-extension'),
    __('sidebar', 'elfsight-elementor-extension'),
    __('testimonial', 'elfsight-elementor-extension'),
    __('transaction', 'elfsight-elementor-extension'),
    __('donate', 'elfsight-elementor-extension'),
    __('donation', 'elfsight-elementor-extension'),
    __('sales', 'elfsight-elementor-extension'),
    __('tax', 'elfsight-elementor-extension'),
    __('merchant', 'elfsight-elementor-extension'),
    __('visa', 'elfsight-elementor-extension'),
    __('mastercard', 'elfsight-elementor-extension'),
    __('timer', 'elfsight-elementor-extension'),
    __('clock', 'elfsight-elementor-extension'),
    __('countup', 'elfsight-elementor-extension'),
    __('wedding', 'elfsight-elementor-extension'),
    __('holiday', 'elfsight-elementor-extension'),
    __('birthday', 'elfsight-elementor-extension'),
    __('counter', 'elfsight-elementor-extension'),
    __('hit', 'elfsight-elementor-extension'),
    __('banner', 'elfsight-elementor-extension'),
    __('notification', 'elfsight-elementor-extension'),
    __('alert', 'elfsight-elementor-extension'),
    __('warning', 'elfsight-elementor-extension'),
    __('announcement', 'elfsight-elementor-extension'),
    __('discount', 'elfsight-elementor-extension'),
    __('coupon', 'elfsight-elementor-extension'),
    __('scarcity', 'elfsight-elementor-extension'),
    __('urgency', 'elfsight-elementor-extension'),
    __('promotion', 'elfsight-elementor-extension'),
    __('conversion', 'elfsight-elementor-extension'),
    __('fomo', 'elfsight-elementor-extension'),
    __('action', 'elfsight-elementor-extension'),
    __('event', 'elfsight-elementor-extension'),
    __('offer', 'elfsight-elementor-extension'),
    __('time', 'elfsight-elementor-extension'),
    __('launch', 'elfsight-elementor-extension'),
    __('christmas', 'elfsight-elementor-extension'),
    __('black', 'elfsight-elementor-extension'),
    __('pin', 'elfsight-elementor-extension'),
    __('board', 'elfsight-elementor-extension'),
    __('decor', 'elfsight-elementor-extension'),
    __('recipe', 'elfsight-elementor-extension'),
    __('inspiration', 'elfsight-elementor-extension'),
    __('messenger', 'elfsight-elementor-extension'),
    __('communication', 'elfsight-elementor-extension'),
    __('conversation', 'elfsight-elementor-extension'),
    __('talk', 'elfsight-elementor-extension'),
    __('viber', 'elfsight-elementor-extension'),
    __('telegram', 'elfsight-elementor-extension'),
    __('whatsapp', 'elfsight-elementor-extension'),
    __('dialog', 'elfsight-elementor-extension'),
    __('lead', 'elfsight-elementor-extension'),
    __('convert', 'elfsight-elementor-extension'),
    __('hotel', 'elfsight-elementor-extension'),
    __('restaurant', 'elfsight-elementor-extension'),
    __('home', 'elfsight-elementor-extension'),
    __('rental', 'elfsight-elementor-extension'),
    __('host', 'elfsight-elementor-extension'),
    __('house', 'elfsight-elementor-extension'),
    __('hostel', 'elfsight-elementor-extension'),
    __('inn', 'elfsight-elementor-extension'),
    __('guest', 'elfsight-elementor-extension'),
    __('tripadvisor', 'elfsight-elementor-extension'),
    __('aboutus', 'elfsight-elementor-extension'),
    __('member', 'elfsight-elementor-extension'),
    __('meet', 'elfsight-elementor-extension'),
    __('band', 'elfsight-elementor-extension'),
    __('teacher', 'elfsight-elementor-extension'),
    __('doctor', 'elfsight-elementor-extension'),
    __('company', 'elfsight-elementor-extension'),
    __('roster', 'elfsight-elementor-extension'),
    __('contact', 'elfsight-elementor-extension'),
    __('position', 'elfsight-elementor-extension'),
    __('card', 'elfsight-elementor-extension'),
    __('staff', 'elfsight-elementor-extension'),
    __('view', 'elfsight-elementor-extension'),
    __('read', 'elfsight-elementor-extension'),
    __('download', 'elfsight-elementor-extension'),
    __('document', 'elfsight-elementor-extension'),
    __('adobe', 'elfsight-elementor-extension'),
    __('file', 'elfsight-elementor-extension'),
    __('pdf', 'elfsight-elementor-extension'),
    __('doc', 'elfsight-elementor-extension'),
    __('xls', 'elfsight-elementor-extension'),
    __('word', 'elfsight-elementor-extension'),
    __('excel', 'elfsight-elementor-extension'),
    __('ppt', 'elfsight-elementor-extension'),
    __('powerpoint', 'elfsight-elementor-extension'),
    __('upload', 'elfsight-elementor-extension'),
    __('google', 'elfsight-elementor-extension'),
    __('microsoft', 'elfsight-elementor-extension'),
    __('text', 'elfsight-elementor-extension'),
    __('sheet', 'elfsight-elementor-extension'),
    __('law', 'elfsight-elementor-extension'),
    __('policy', 'elfsight-elementor-extension'),
    __('eu', 'elfsight-elementor-extension'),
    __('gdpr', 'elfsight-elementor-extension'),
    __('personaldata', 'elfsight-elementor-extension'),
    __('privacy', 'elfsight-elementor-extension'),
    __('check', 'elfsight-elementor-extension'),
    __('verify', 'elfsight-elementor-extension'),
    __('agreement', 'elfsight-elementor-extension'),
    __('disclaimer', 'elfsight-elementor-extension'),
    __('bar', 'elfsight-elementor-extension'),
    __('notice', 'elfsight-elementor-extension'),
    __('information', 'elfsight-elementor-extension'),
    __('maps', 'elfsight-elementor-extension'),
    __('search', 'elfsight-elementor-extension'),
    __('adult', 'elfsight-elementor-extension'),
    __('18', 'elfsight-elementor-extension'),
    __('21', 'elfsight-elementor-extension'),
    __('alcohol', 'elfsight-elementor-extension'),
    __('tobacco', 'elfsight-elementor-extension'),
    __('porn', 'elfsight-elementor-extension'),
    __('marijuana', 'elfsight-elementor-extension'),
    __('cigar', 'elfsight-elementor-extension'),
    __('gate', 'elfsight-elementor-extension'),
    __('child', 'elfsight-elementor-extension'),
    __('protection', 'elfsight-elementor-extension'),
    __('restrict', 'elfsight-elementor-extension'),
    __('access', 'elfsight-elementor-extension'),
    __('inappropriate', 'elfsight-elementor-extension'),
    __('COPPA', 'elfsight-elementor-extension'),
    __('birth', 'elfsight-elementor-extension'),
    __('showcase', 'elfsight-elementor-extension'),
    __('collection', 'elfsight-elementor-extension'),
    __('followers', 'elfsight-elementor-extension'),
    __('phone', 'elfsight-elementor-extension'),
    __('number', 'elfsight-elementor-extension'),
    __('skype', 'elfsight-elementor-extension'),
    __('hangouts', 'elfsight-elementor-extension'),
    __('callback', 'elfsight-elementor-extension'),
    __('voice', 'elfsight-elementor-extension'),
    __('hero', 'elfsight-elementor-extension'),
    __('picture', 'elfsight-elementor-extension'),
    __('forecast', 'elfsight-elementor-extension'),
    __('rain', 'elfsight-elementor-extension'),
    __('snow', 'elfsight-elementor-extension'),
    __('temperature', 'elfsight-elementor-extension'),
    __('celsius', 'elfsight-elementor-extension'),
    __('fahrenheit', 'elfsight-elementor-extension'),
    __('wind', 'elfsight-elementor-extension'),
    __('humidity', 'elfsight-elementor-extension'),
    __('pressure', 'elfsight-elementor-extension'),
    __('meteo', 'elfsight-elementor-extension'),
    __('condition', 'elfsight-elementor-extension'),
    __('partner', 'elfsight-elementor-extension'),
    __('sponsor', 'elfsight-elementor-extension'),
    __('brand', 'elfsight-elementor-extension'),
    __('vendor', 'elfsight-elementor-extension'),
    __('supporter', 'elfsight-elementor-extension'),
    __('featured', 'elfsight-elementor-extension'),
    __('top', 'elfsight-elementor-extension'),
    __('trust', 'elfsight-elementor-extension'),
    __('agenda', 'elfsight-elementor-extension'),
    __('schedule', 'elfsight-elementor-extension'),
    __('rsvp', 'elfsight-elementor-extension'),
    __('upcoming', 'elfsight-elementor-extension'),
    __('ticket', 'elfsight-elementor-extension'),
    __('conference', 'elfsight-elementor-extension'),
    __('festival', 'elfsight-elementor-extension'),
    __('lineup', 'elfsight-elementor-extension'),
    __('week', 'elfsight-elementor-extension'),
    __('month', 'elfsight-elementor-extension'),
    __('date', 'elfsight-elementor-extension'),
    __('timetable', 'elfsight-elementor-extension'),
    __('outlook', 'elfsight-elementor-extension'),
    __('product', 'elfsight-elementor-extension'),
    __('goods', 'elfsight-elementor-extension'),
    __('merchandise', 'elfsight-elementor-extension'),
    __('services', 'elfsight-elementor-extension'),
    __('companies', 'elfsight-elementor-extension'),
    __('mobile', 'elfsight-elementor-extension'),
    __('thumbnail', 'elfsight-elementor-extension'),
    __('masonry', 'elfsight-elementor-extension'),
    __('collage', 'elfsight-elementor-extension'),
    __('landscape', 'elfsight-elementor-extension'),
    __('portrait', 'elfsight-elementor-extension'),
    __('square', 'elfsight-elementor-extension'),
    __('panorama', 'elfsight-elementor-extension'),
    __('tile', 'elfsight-elementor-extension'),
    __('photography', 'elfsight-elementor-extension'),
    __('art', 'elfsight-elementor-extension'),
    __('creative', 'elfsight-elementor-extension'),
    __('lightbox', 'elfsight-elementor-extension'),
    __('justified', 'elfsight-elementor-extension'),
    __('podcast', 'elfsight-elementor-extension'),
    __('background', 'elfsight-elementor-extension'),
    __('music', 'elfsight-elementor-extension'),
    __('radio', 'elfsight-elementor-extension'),
    __('stream', 'elfsight-elementor-extension'),
    __('track', 'elfsight-elementor-extension'),
    __('show', 'elfsight-elementor-extension'),
    __('soundcloud', 'elfsight-elementor-extension'),
    __('spotify', 'elfsight-elementor-extension'),
    __('apple', 'elfsight-elementor-extension'),
    __('amazon', 'elfsight-elementor-extension'),
    __('audiobook', 'elfsight-elementor-extension'),
    __('sound', 'elfsight-elementor-extension'),
    __('song', 'elfsight-elementor-extension'),
    __('audio', 'elfsight-elementor-extension'),
    __('stitcher', 'elfsight-elementor-extension'),
    __('autoplay', 'elfsight-elementor-extension'),
    __('play', 'elfsight-elementor-extension'),
    __('compare', 'elfsight-elementor-extension'),
    __('comparison', 'elfsight-elementor-extension'),
    __('casestudy', 'elfsight-elementor-extension'),
    __('difference', 'elfsight-elementor-extension'),
    __('scroll', 'elfsight-elementor-extension'),
    __('long', 'elfsight-elementor-extension'),
    __('button', 'elfsight-elementor-extension'),
    __('go', 'elfsight-elementor-extension'),
    __('return', 'elfsight-elementor-extension'),
    __('qrcode', 'elfsight-elementor-extension'),
    __('bitcoin', 'elfsight-elementor-extension'),
    __('vcard', 'elfsight-elementor-extension'),
    __('progress', 'elfsight-elementor-extension'),
    __('value', 'elfsight-elementor-extension'),
    __('achievements', 'elfsight-elementor-extension'),
    __('up', 'elfsight-elementor-extension'),
    __('stat', 'elfsight-elementor-extension'),
    __('animated', 'elfsight-elementor-extension'),
    __('fact', 'elfsight-elementor-extension'),
    __('count', 'elfsight-elementor-extension'),
    __('dish', 'elfsight-elementor-extension'),
    __('drink', 'elfsight-elementor-extension'),
    __('food', 'elfsight-elementor-extension'),
    __('cafe', 'elfsight-elementor-extension'),
    __('coffeehouse', 'elfsight-elementor-extension'),
    __('fastfood', 'elfsight-elementor-extension'),
    __('pizza', 'elfsight-elementor-extension'),
    __('breakfast', 'elfsight-elementor-extension'),
    __('lunch', 'elfsight-elementor-extension'),
    __('dinner', 'elfsight-elementor-extension'),
    __('wine', 'elfsight-elementor-extension'),
    __('views', 'elfsight-elementor-extension'),
    __('visit', 'elfsight-elementor-extension'),
    __('analytics', 'elfsight-elementor-extension'),
    __('traffic', 'elfsight-elementor-extension'),
    __('online', 'elfsight-elementor-extension'),
    __('realtime', 'elfsight-elementor-extension'),
    __('field', 'elfsight-elementor-extension'),
    __('box', 'elfsight-elementor-extension')
);
